---
swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: ms-login
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: "/"
tags:
- name: login-controller
  description: User Controller
paths:
  "/api/login":
    post:
      tags:
      - user-controller
      summary: login
      operationId: loginUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - in: body
        name: user
        description: user
        required: true
        schema:
          "$ref": "#/definitions/Login"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Token"
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  "/api/validateToken":
    post:
      tags:
      - user-controller
      summary: validate
      operationId: validateUsingPOST
      consumes:
      - application/json
      produces:
      - "*/*"
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Login:
    type: object
    properties:
      password:
        type: string
      username:
        type: string
    title: Login
  Token:
    type: object
    properties:
      autenticacion:
        type: boolean
      token:
        type: string
    title: Token
